### ISSUE TITLE
Support of vector-data

### ISSUE THREAD

**Issue by ErikWessel** [PaVoS-TECO/core#19]
### Current state
vector-data is already being stored in ArrayLists of type Double
### TODO
+ need to rewrite / add code sections for the processing of vector-data

**Comment by olivermliu** [comment]
Have you implemented the TODOs for database already? Based on d2646a4 it looks like you have. I'm sorry I haven't gotten around to doing that earlier.

**Comment by ErikWessel** [comment]
@olivermliu I have implemented them in a simple way.
If you have some spare time, it would be nice if you could check more thoroughly! 😄
Just check for `getVectorObservations() ` & `getAnonObservation()` in your code

**Comment by ErikWessel** [comment]
https://github.com/PaVoS-TECO/core/commit/1760659fdd505c930da19d4c3d4cc0d5af0f5a41
+ completed rest of TODOs

**Comment by ErikWessel** [comment]
https://github.com/PaVoS-TECO/core/commit/1760659fdd505c930da19d4c3d4cc0d5af0f5a41
+ completed rest of TODOs
